package radio.ui;

import radio.service.GenreService;
import radio.service.PlaylistGenerator;
import radio.service.RadioManagerService;
import radio.model.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author funes
 */
public class ProgramsPanel extends javax.swing.JPanel {
    private GenreService genreSvc;
    private PlaylistGenerator generator;
    private RadioManagerService svc;

    private DefaultTableModel programsModel;
    
    public void bindServices(GenreService genreSvc, PlaylistGenerator generator, RadioManagerService svc) {
        this.genreSvc = genreSvc;
        this.generator = generator;
        this.svc = svc;

        setupProgramsTable();
        fillGenreCombo();
        refreshProgramsTable();

        attachNumericFilterToDuration();

        // Enter dispara "Add Program" si ya hay root pane
        if (getRootPane() != null) getRootPane().setDefaultButton(btnAddProgramPrograms);
    }
    
    
    // === Helpers de validación/parseo ===
    private static String req(String v, String field) {
        if (v == null || v.trim().isEmpty()) throw new IllegalArgumentException(field + " is required");
        return v.trim();
    }
    private static int parseIntSafe(String s) {
        try { return Integer.parseInt(s.trim()); }
        catch (Exception e) { throw new IllegalArgumentException("Duration must be a positive integer"); }
    }
    private static int pos(int m, String field) {
        if (m <= 0) throw new IllegalArgumentException(field + " must be > 0");
        return m;
    }

    /** Permite solo dígitos en Duration */
    private void attachNumericFilterToDuration() {
        txfBoxDurationPrograms.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) && c != java.awt.event.KeyEvent.VK_BACK_SPACE
                        && c != java.awt.event.KeyEvent.VK_DELETE) {
                 evt.consume();
                }
            }
        });
    }

    private void setupProgramsTable() {
        programsModel = new DefaultTableModel(new Object[]{"Name","Schedule","Duration","Genre","Announcer"}, 0) {
            @Override public boolean isCellEditable(int r,int c){ return false; }
        };
    TableBoxPrograms.setModel(programsModel);
    }
    
    private void fillGenreCombo() {
        cbxPrograms.removeAllItems();
        // lista desde el servicio
        for (String g : genreSvc.listAll()) cbxPrograms.addItem(g);
        cbxPrograms.addItem("OTHER");
        cbxPrograms.setSelectedIndex(0);
    }
    
    private void refreshProgramsTable() {
        programsModel.setRowCount(0);
        try {
            for (Program p : svc.listPrograms()) {
                 programsModel.addRow(new Object[]{
                 p.getName(), p.getSchedule(), p.getDurationMinutes(),
                 p.getGenre(), p.getAnnouncer().getFullName()
                });
            }
        } catch (IllegalStateException ex) { /* estación no creada */ }
    }
    
    private void clearProgForm() {
        txfBoxNamePrograms.setText("");
        txfBoxShedulePrograms.setText("");
        txfBoxDurationPrograms.setText("");
        txfBoxAnnuncersPrograms.setText("");
        if (cbxPrograms.getItemCount() > 0) cbxPrograms.setSelectedIndex(0);
    }
    
    // Busca Announcer por ID o por nombre exacto
    private Announcer findAnnouncer(String input) {
        String q = input == null ? "" : input.trim();
        for (Announcer a : svc.getStation().getAnnouncers()) {
            if (a.getId().equalsIgnoreCase(q) || a.getFullName().equalsIgnoreCase(q)) return a;
        }
        return null;
    }
  
    public ProgramsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProgramsPanel = new javax.swing.JPanel();
        lblTitleProgramsPanel = new javax.swing.JLabel();
        pnlSettingProgrmas = new javax.swing.JPanel();
        lblNamePrograms = new javax.swing.JLabel();
        lblSchedulePrograms = new javax.swing.JLabel();
        lblGenrePrograms = new javax.swing.JLabel();
        lblAnnouncersPrograms = new javax.swing.JLabel();
        txfBoxNamePrograms = new javax.swing.JTextField();
        txfBoxShedulePrograms = new javax.swing.JTextField();
        txfBoxAnnuncersPrograms = new javax.swing.JTextField();
        btnOthrePrograms = new javax.swing.JButton();
        btnAddProgramPrograms = new javax.swing.JButton();
        lblDurationPrograms = new javax.swing.JLabel();
        txfBoxDurationPrograms = new javax.swing.JTextField();
        btnCrearProgram = new javax.swing.JButton();
        cbxPrograms = new javax.swing.JComboBox<>();
        pnlTablePrograms = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBoxPrograms = new javax.swing.JTable();

        pnlProgramsPanel.setBackground(new java.awt.Color(77, 98, 91));

        lblTitleProgramsPanel.setBackground(new java.awt.Color(168, 178, 130));
        lblTitleProgramsPanel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitleProgramsPanel.setForeground(new java.awt.Color(168, 178, 130));
        lblTitleProgramsPanel.setText("Programs");

        pnlSettingProgrmas.setBackground(new java.awt.Color(245, 247, 246));
        pnlSettingProgrmas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));

        lblNamePrograms.setForeground(new java.awt.Color(60, 63, 65));
        lblNamePrograms.setText("Name:");

        lblSchedulePrograms.setForeground(new java.awt.Color(60, 63, 65));
        lblSchedulePrograms.setText("Shedule:");

        lblGenrePrograms.setForeground(new java.awt.Color(60, 63, 65));
        lblGenrePrograms.setText("Genre:");

        lblAnnouncersPrograms.setForeground(new java.awt.Color(60, 63, 65));
        lblAnnouncersPrograms.setText("Announcer:");

        txfBoxNamePrograms.setBackground(new java.awt.Color(245, 247, 246));
        txfBoxNamePrograms.setText("Name...");
        txfBoxNamePrograms.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(204, 204, 204)));
        txfBoxNamePrograms.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txfBoxNamePrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBoxNameProgramsActionPerformed(evt);
            }
        });

        txfBoxShedulePrograms.setBackground(new java.awt.Color(245, 247, 246));
        txfBoxShedulePrograms.setText("Shedule...");
        txfBoxShedulePrograms.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(204, 204, 204)));
        txfBoxShedulePrograms.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txfBoxShedulePrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBoxSheduleProgramsActionPerformed(evt);
            }
        });

        txfBoxAnnuncersPrograms.setBackground(new java.awt.Color(245, 247, 246));
        txfBoxAnnuncersPrograms.setText("Numbers...");
        txfBoxAnnuncersPrograms.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(204, 204, 204)));
        txfBoxAnnuncersPrograms.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txfBoxAnnuncersPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBoxAnnuncersProgramsActionPerformed(evt);
            }
        });

        btnOthrePrograms.setBackground(new java.awt.Color(168, 178, 130));
        btnOthrePrograms.setForeground(new java.awt.Color(255, 255, 255));
        btnOthrePrograms.setText("Other..");
        btnOthrePrograms.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOthrePrograms.setBorderPainted(false);
        btnOthrePrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOthreProgramsActionPerformed(evt);
            }
        });

        btnAddProgramPrograms.setBackground(new java.awt.Color(168, 178, 130));
        btnAddProgramPrograms.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProgramPrograms.setText("Add Program");
        btnAddProgramPrograms.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddProgramPrograms.setBorderPainted(false);
        btnAddProgramPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProgramProgramsActionPerformed(evt);
            }
        });

        lblDurationPrograms.setForeground(new java.awt.Color(60, 63, 65));
        lblDurationPrograms.setText("Duration (min):");

        txfBoxDurationPrograms.setBackground(new java.awt.Color(245, 247, 246));
        txfBoxDurationPrograms.setText("min");
        txfBoxDurationPrograms.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 0, new java.awt.Color(204, 204, 204)));
        txfBoxDurationPrograms.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txfBoxDurationPrograms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfBoxDurationProgramsActionPerformed(evt);
            }
        });

        btnCrearProgram.setBackground(new java.awt.Color(168, 178, 130));
        btnCrearProgram.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearProgram.setText("Clear");
        btnCrearProgram.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearProgram.setBorderPainted(false);
        btnCrearProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProgramActionPerformed(evt);
            }
        });

        cbxPrograms.setBackground(new java.awt.Color(245, 247, 246));
        cbxPrograms.setEditable(true);
        cbxPrograms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Música Clásica", "Blues", "Jazz", "Soul", "R&B", "Rock", "Pop", "Hip Hop", "Country", "Música Electrónica", "Reggae", "Disco", "Salsa", "Cumbia", "Bachata", "Reguetón" }));

        javax.swing.GroupLayout pnlSettingProgrmasLayout = new javax.swing.GroupLayout(pnlSettingProgrmas);
        pnlSettingProgrmas.setLayout(pnlSettingProgrmasLayout);
        pnlSettingProgrmasLayout.setHorizontalGroup(
            pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingProgrmasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNamePrograms)
                    .addComponent(lblSchedulePrograms)
                    .addComponent(lblDurationPrograms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfBoxShedulePrograms, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfBoxNamePrograms, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfBoxDurationPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSettingProgrmasLayout.createSequentialGroup()
                        .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSettingProgrmasLayout.createSequentialGroup()
                                .addComponent(btnAddProgramPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCrearProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSettingProgrmasLayout.createSequentialGroup()
                                .addComponent(lblGenrePrograms)
                                .addGap(246, 246, 246)
                                .addComponent(btnOthrePrograms, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65))
                    .addGroup(pnlSettingProgrmasLayout.createSequentialGroup()
                        .addComponent(lblAnnouncersPrograms)
                        .addGap(41, 41, 41)
                        .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfBoxAnnuncersPrograms)
                            .addComponent(cbxPrograms, 0, 162, Short.MAX_VALUE))
                        .addGap(143, 143, 143))))
        );
        pnlSettingProgrmasLayout.setVerticalGroup(
            pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingProgrmasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamePrograms)
                    .addComponent(lblGenrePrograms)
                    .addComponent(txfBoxNamePrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOthrePrograms)
                    .addComponent(cbxPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAnnouncersPrograms)
                        .addComponent(txfBoxAnnuncersPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSchedulePrograms)
                        .addComponent(txfBoxShedulePrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSettingProgrmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDurationPrograms)
                    .addComponent(txfBoxDurationPrograms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddProgramPrograms)
                    .addComponent(btnCrearProgram))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTablePrograms.setBackground(new java.awt.Color(245, 247, 246));
        pnlTablePrograms.setBorder(new javax.swing.border.MatteBorder(null));

        TableBoxPrograms.setBackground(new java.awt.Color(245, 247, 246));
        TableBoxPrograms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Schedule", "Duration", "Genre", "Announcer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TableBoxPrograms.setFocusable(false);
        TableBoxPrograms.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableBoxPrograms.setSelectionBackground(new java.awt.Color(245, 247, 246));
        TableBoxPrograms.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableBoxPrograms);

        javax.swing.GroupLayout pnlTableProgramsLayout = new javax.swing.GroupLayout(pnlTablePrograms);
        pnlTablePrograms.setLayout(pnlTableProgramsLayout);
        pnlTableProgramsLayout.setHorizontalGroup(
            pnlTableProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlTableProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableProgramsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlTableProgramsLayout.setVerticalGroup(
            pnlTableProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
            .addGroup(pnlTableProgramsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlProgramsPanelLayout = new javax.swing.GroupLayout(pnlProgramsPanel);
        pnlProgramsPanel.setLayout(pnlProgramsPanelLayout);
        pnlProgramsPanelLayout.setHorizontalGroup(
            pnlProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProgramsPanelLayout.createSequentialGroup()
                        .addComponent(lblTitleProgramsPanel)
                        .addGap(0, 613, Short.MAX_VALUE))
                    .addGroup(pnlProgramsPanelLayout.createSequentialGroup()
                        .addGroup(pnlProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlSettingProgrmas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(pnlTablePrograms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlProgramsPanelLayout.setVerticalGroup(
            pnlProgramsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProgramsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitleProgramsPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSettingProgrmas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTablePrograms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProgramsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProgramsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txfBoxNameProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBoxNameProgramsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfBoxNameProgramsActionPerformed

    private void txfBoxSheduleProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBoxSheduleProgramsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfBoxSheduleProgramsActionPerformed

    private void txfBoxAnnuncersProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBoxAnnuncersProgramsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfBoxAnnuncersProgramsActionPerformed

    private void btnOthreProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOthreProgramsActionPerformed
        try {
            String g = JOptionPane.showInputDialog(this, "New genre:");
            if (g == null || g.isBlank()) return;
            String ensured = genreSvc.ensure(g.trim());
            fillGenreCombo();
            cbxPrograms.setSelectedItem(ensured);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnOthreProgramsActionPerformed

    private void btnAddProgramProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProgramProgramsActionPerformed
        try {
            if (svc == null) {
                JOptionPane.showMessageDialog(this, "Services not bound. Open panel from the main menu.");
                return;
            }

            String name     = req(txfBoxNamePrograms.getText(), "Name");
            String schedule = req(txfBoxShedulePrograms.getText(), "Schedule");
            int duration    = pos(parseIntSafe(txfBoxDurationPrograms.getText()), "Duration");
            String annTxt   = req(txfBoxAnnuncersPrograms.getText(), "Announcer");
            Object sel      = cbxPrograms.getSelectedItem();
            if (sel == null) { JOptionPane.showMessageDialog(this, "Genre is required"); return; }

            String genre = sel.toString();
            if ("OTHER".equalsIgnoreCase(genre)) {
                String g = JOptionPane.showInputDialog(this, "New genre:");
                if (g == null || g.isBlank()) return;
                genre = genreSvc.ensure(g.trim());
                fillGenreCombo();
                cbxPrograms.setSelectedItem(genre);
            } else {
                genre = genreSvc.ensure(genre); // normaliza/asegura
            }

            // Buscar locutor por ID o nombre exacto (tu método)
            Announcer ann = findAnnouncer(annTxt);
            if (ann == null) {
                JOptionPane.showMessageDialog(this, "Announcer not found (use ID or exact name)");
                return;
            }

            // Registrar (service valida unicidad por nombre y duración > 0)
            svc.registerProgram(name, schedule, duration, genre, ann);

            refreshProgramsTable();
            clearProgForm();
            JOptionPane.showMessageDialog(this, "Program added");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
             
    }//GEN-LAST:event_btnAddProgramProgramsActionPerformed

    private void txfBoxDurationProgramsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfBoxDurationProgramsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfBoxDurationProgramsActionPerformed

    private void btnCrearProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProgramActionPerformed
        clearProgForm();
    }//GEN-LAST:event_btnCrearProgramActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableBoxPrograms;
    private javax.swing.JButton btnAddProgramPrograms;
    private javax.swing.JButton btnCrearProgram;
    private javax.swing.JButton btnOthrePrograms;
    private javax.swing.JComboBox<String> cbxPrograms;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnnouncersPrograms;
    private javax.swing.JLabel lblDurationPrograms;
    private javax.swing.JLabel lblGenrePrograms;
    private javax.swing.JLabel lblNamePrograms;
    private javax.swing.JLabel lblSchedulePrograms;
    private javax.swing.JLabel lblTitleProgramsPanel;
    private javax.swing.JPanel pnlProgramsPanel;
    private javax.swing.JPanel pnlSettingProgrmas;
    private javax.swing.JPanel pnlTablePrograms;
    private javax.swing.JTextField txfBoxAnnuncersPrograms;
    private javax.swing.JTextField txfBoxDurationPrograms;
    private javax.swing.JTextField txfBoxNamePrograms;
    private javax.swing.JTextField txfBoxShedulePrograms;
    // End of variables declaration//GEN-END:variables
}
